name: CI

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main

jobs:
  lint:
    name: Prettier, ESLint, and TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js 20.9.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node_modules-v1-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node_modules-

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: npm run prettier

      - name: Run ESLint
        run: npm run lint

      - name: Run TypeScript
        run: npm run typecheck

  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js 20.9.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node_modules-v1-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node_modules-

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
